image: node:12-alpine

stages:
  - build
  - test

cache:
  paths:
    - node_modules

build:
  stage: build
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/

lint:
  stage: test
  before_script:
    - npm install -g @angular/cli
  script:
    - ng lint
