version: '3.7'
services:
  crush-them-all:
    container_name: crush-them-all
    build:
      context: .
      target: node-development
    volumes:
      - '.:/usr/src/app'
    ports:
      - '4200:4200'
    command: sh -c "npm install && ng serve --host 0.0.0.0 --port 4200"
